### ISSUE TITLE
fork?

### ISSUE THREAD

**Issue by zero-systems** [fafhrd91/actix-web-postmortem#11]
Actix is a great tool for development high-load applicatons. And it would be even better.
I don't want to switch this crate because it's real fast and easy to use.
Actix showed me a way to write fast and powerful code. And I want to fork this repo.
But I am not much experienced as Nikolay and I don't have a lot of free time for that. I mean maybe people who really want to develop rust ecosystem can help project by forking it? If it would so, I don't mind to become maintainer.

**Comment by thorjelly** [comment]
I would say we wait and see what the maintainer ultimately decides to do with the project. If worse comes to worse, I do hope someone creates an actively maintained fork. It was a large project that had a lot of people using it, and was an important part of the Rust ecosystem.

I understand and completely respect and appreciate what Nikolay did for us creating and maintaining such an amazing project, I understand and respect the frustration he felt, I respect that he decided to have nothing to do with it or the community anymore, and I truly hope that the Rust community learns from this and grows up. But I also feel like since the news story broke, a lot of the people who came here, who are commenting, are in the luxury of not actually relying on this software and only want this to be a hard lesson. A lot of people want to respect the maintainer's wishes and let the project die, but that really throws a lot of people who were relying on it under a bus, who had nothing to do with the drama, who only tried to make the best decision of what crates to build their project from, and then suddenly got caught up in all of this. We shouldn't forget that one of the ideals of the OO community is that code is available to everyone, to be forked, maintained, and changed freely.

So, again. Right now we should wait, see what happens. But there should be nothing wrong with someone creating and actively maintaining fork of actix-web. I just hope that if someone does, they don't get harassed for it too. Because then we've really learned nothing.

**Comment by stappersg** [comment]
There is [homesteading principle](https://en.wikipedia.org/wiki/Homestead_principle).

Right now (2020-01-20) there is the fresh announcement that https://github.com/actix will be abonded.

Sad, but true.

But unlike unowned land, can an unowned github.com project not get an act of [original appropriation](https://en.wikipedia.org/wiki/Original_appropriation).

I do hope that several people get granted _full actix project privilege_  with one obligation: _care-taking of the project_.  The very minimum of that task will be handing over `actix` to a next generation of care-takers.
